### ISSUE TITLE
查看demo时跟预期不符

### ISSUE THREAD

**Issue by 768446472** [waitingsong/LinkageSel#11]
作者你好：
我使用的是谷歌浏览器，版本如下
Google Chrome
版本 75.0.3770.142（正式版本） （64 位）
GreenChrome 6.6.6

当我查看DEMO时出现了跟README的展示图片不同的现象。
![image](https://user-images.githubusercontent.com/46511915/61691445-291fed00-ad5e-11e9-99a8-57287b9075b7.png)

期待您的回复。

**Comment by 768446472** [comment]
对不起，我提交到了错误的GIT项目里。

**Comment by waitingsong** [comment]
(^-^)
